_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 5037884e-746a-443a-baac-9f8591fd14aa
name: 'Drupal Manga'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /home-page
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
