<?php

/**
 * @file
 * Primary module hooks for Main module.
 */

/**
 * Implements hook_theme() for main pages.
 */
function main_theme() {
  return [
    'rich_content_menu' => [
      'template' => 'rich-content-menu',
      'variables' => [
        'data' => [],
      ],
    ],
    'main_manga_form' => [
      'render element' => 'form',
    ],
    'main_chapter_form' => [
      'render element' => 'form',
    ],
    'manga_list' => [
      'template' => 'manga-list',
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}
